// marlin_host.cu — vLLM 增强 Marlin 的裸指针 host 发射器。
//
// ported from packages/vllm/csrc/libtorch_stable/quantization/marlin/marlin.cu
// @ 本机 vllm fork(marlin_mm + exec-config 启发式逐段移植;torch::stable::Tensor
// 解绑为 void*/int 形参,STD_TORCH_CHECK 改为错误码返回)。
// kernel 实例:csrc/vllm_marlin/sm80_kernel_float16_u4_float16.cu(f16 A / u4 B /
// f16 C / f16 scales,auto-generated by vllm generate_kernels.py,零 torch)。
//
// 本 POC 路径固化:no act-order / no zp / no bias / use_atomic_add=false /
// use_fp32_reduce=false(C 全量写,无需预清零;C_tmp 不触碰)。

#include <cuda_runtime.h>
#include <cstdio>
#include <cstdlib>

#include "kernel.h"
#include "marlin.cuh"

using namespace MARLIN_NAMESPACE_NAME;

namespace {

__global__ void MarlinDefault(MARLIN_KERNEL_PARAMS){};

using MarlinFuncPtr = void (*)(MARLIN_KERNEL_PARAMS);

typedef struct {
  int thread_k;
  int thread_n;
  int num_threads;
} thread_config_t;

thread_config_t small_batch_thread_configs[] = {
    // Ordered by priority
    {128, 128, 256},
    {64, 128, 128},
    {128, 64, 128}};

thread_config_t large_batch_thread_configs[] = {
    // Ordered by priority
    {64, 256, 256},
    {64, 128, 128},
    {128, 64, 128}};

typedef struct {
  int blocks_per_sm;
  thread_config_t tb_cfg;
} exec_config_t;

int get_scales_cache_size(thread_config_t const& th_config, int prob_m,
                          int prob_n, int prob_k, int num_bits, int group_size,
                          bool has_act_order, bool is_k_full, int stages) {
  bool cache_scales_chunk = has_act_order && !is_k_full;

  int tb_n = th_config.thread_n;
  int tb_k = th_config.thread_k;

  int tb_groups;
  if (group_size == -1) {
    tb_groups = 1;
  } else if (group_size == 0) {
    tb_groups = div_ceil(tb_k, 32);
  } else {
    tb_groups = div_ceil(tb_k, group_size);
  }

  if (cache_scales_chunk) {
    int load_groups = tb_groups * stages * 2;
    load_groups = load_groups > 32 ? load_groups : 32;
    return load_groups * tb_n * 2;
  } else {
    int tb_scales = tb_groups * tb_n * 2;
    return tb_scales * stages;
  }
}

int get_kernel_cache_size(thread_config_t const& th_config,
                          int thread_m_blocks, int prob_m, int prob_n,
                          int prob_k, int num_bits, int group_size,
                          bool has_act_order, bool is_k_full, bool has_zp,
                          bool is_zp_float, bool is_a_8bit, int stages) {
  int pack_factor = 32 / num_bits;

  int tb_k = th_config.thread_k;
  int tb_n = th_config.thread_n;
  int tb_m = thread_m_blocks * 16;
  int sh_a_size = stages * (tb_m * tb_k) * (is_a_8bit ? 1 : 2);
  int sh_b_size = stages * (tb_k * tb_n / pack_factor) * 4;
  int sh_red_size = tb_m * (tb_n + 8) * 2;
  int sh_bias_size = tb_n * 2;
  int tmp_size =
      (sh_b_size > sh_red_size ? sh_red_size : sh_b_size) + sh_bias_size;
  tmp_size = (sh_b_size > tmp_size ? sh_b_size : tmp_size);
  tmp_size = (sh_red_size > tmp_size ? sh_red_size : tmp_size);

  int sh_s_size =
      get_scales_cache_size(th_config, prob_m, prob_n, prob_k, num_bits,
                            group_size, has_act_order, is_k_full, stages);
  int sh_g_idx_size = has_act_order && !is_k_full ? stages * tb_k / 4 : 0;
  int sh_zp_size = 0;
  if (has_zp) {
    if (is_zp_float)
      sh_zp_size = sh_s_size;
    else if (num_bits == 4)
      sh_zp_size = sh_s_size / 4;
    else if (num_bits == 8)
      sh_zp_size = sh_s_size / 2;
  }

  return tmp_size + sh_a_size + sh_s_size + sh_zp_size + sh_g_idx_size;
}

bool is_valid_config(thread_config_t const& th_config, int thread_m_blocks,
                     int prob_m, int prob_n, int prob_k, int num_bits,
                     int group_size, bool has_act_order, bool is_k_full,
                     bool has_zp, bool is_zp_float, bool is_a_8bit, int stages,
                     int max_shared_mem) {
  if (th_config.thread_k == -1 || th_config.thread_n == -1 ||
      th_config.num_threads == -1) {
    return false;
  }
  if (prob_k % th_config.thread_k != 0 || prob_n % th_config.thread_n != 0) {
    return false;
  }
  if (th_config.thread_n < min_thread_n || th_config.thread_k < min_thread_k) {
    return false;
  }
  if (th_config.num_threads < 128) {
    return false;
  }
  int cache_size = get_kernel_cache_size(
      th_config, thread_m_blocks, prob_m, prob_n, prob_k, num_bits, group_size,
      has_act_order, is_k_full, has_zp, is_zp_float, is_a_8bit, stages);
  return cache_size <= max_shared_mem;
}

MarlinFuncPtr get_marlin_kernel(
    const vllm::ScalarType a_type, const vllm::ScalarType b_type,
    const vllm::ScalarType c_type, const vllm::ScalarType s_type,
    int thread_m_blocks, int thread_n_blocks, int thread_k_blocks,
    bool m_block_size_8, bool has_act_order, bool has_zp, int group_blocks,
    int threads, bool is_zp_float, int stages) {
  int num_bits = b_type.size_bits();
  auto kernel = MarlinDefault;

  // clang-format off
  #include "kernel_selector.h"
  // clang-format on

  return kernel;
}

exec_config_t determine_exec_config(
    const vllm::ScalarType& a_type, const vllm::ScalarType& b_type,
    const vllm::ScalarType& c_type, const vllm::ScalarType& s_type, int prob_m,
    int prob_n, int prob_k, int thread_m_blocks, bool m_block_size_8,
    int num_bits, int group_size, bool has_act_order, bool is_k_full,
    bool has_zp, bool is_zp_float, int is_a_8bit, int stages,
    int max_shared_mem, int sms) {
  exec_config_t exec_cfg = exec_config_t{1, thread_config_t{-1, -1, -1}};
  thread_config_t* thread_configs = thread_m_blocks > 1
                                        ? large_batch_thread_configs
                                        : small_batch_thread_configs;
  int thread_configs_size =
      thread_m_blocks > 1
          ? sizeof(large_batch_thread_configs) / sizeof(thread_config_t)
          : sizeof(small_batch_thread_configs) / sizeof(thread_config_t);

  for (int i = 0; i < thread_configs_size; i++) {
    thread_config_t th_config = thread_configs[i];

    if (!is_valid_config(th_config, thread_m_blocks, prob_m, prob_n, prob_k,
                         num_bits, group_size, has_act_order, is_k_full,
                         has_zp, is_zp_float, is_a_8bit, stages,
                         max_shared_mem - 512)) {
      continue;
    }

    int group_blocks = 0;
    if (!has_act_order) {
      group_blocks = group_size == -1 ? -1 : group_size / 16;
    }

    auto kernel =
        get_marlin_kernel(a_type, b_type, c_type, s_type, thread_m_blocks,
                          th_config.thread_n / 16, th_config.thread_k / 16,
                          m_block_size_8, has_act_order, has_zp, group_blocks,
                          th_config.num_threads, is_zp_float, stages);

    if (kernel == MarlinDefault) continue;

    return {1, th_config};
  }

  return exec_cfg;
}

// port of marlin.cu::marlin_mm(torch 解绑;仅 W4A16 无 act-order/zp 路径)。
// 返回 0 = ok;3 = 无可用 kernel 配置;4 = 形状非法;5 = 设备能力不足。
int marlin_mm(const void* A, const void* B, void* C, void* c_tmp, void* b_s,
              const void* a_s, bool a_is_s8, const void* b_z, bool use_zp,
              int prob_m, int prob_n, int prob_k, int lda, void* workspace,
              int num_groups, int group_size, int dev, cudaStream_t stream,
              int thread_k_init, int thread_n_init, int sms, bool is_bf16) {
  if (prob_m <= 0 || prob_n <= 0 || prob_k <= 0) return 4;

  constexpr bool has_act_order = false;
  const bool has_zp = use_zp;  // P5-Q1a: kU4(AWQ 非对称,zp int4 打包)路径
  constexpr bool is_zp_float = false;
  constexpr bool is_k_full = false;
  const bool is_a_8bit = a_is_s8;  // A = fp16/bf16(16bit)或 int8(8bit)

  int group_blocks = 0;
  if (group_size == -1) {
    group_blocks = -1;
  } else {
    group_blocks = group_size / 16;
    if (prob_k % group_blocks != 0) return 4;
  }

  int num_bits = 4;
  const int4* A_ptr = (const int4*)A;
  const int4* B_ptr = (const int4*)B;
  int4* C_ptr = (int4*)C;
  const int4* b_s_ptr = (const int4*)b_s;
  int* locks = (int*)workspace;

  int max_shared_mem = 0;
  cudaDeviceGetAttribute(&max_shared_mem,
                         cudaDevAttrMaxSharedMemoryPerBlockOptin, dev);
  if (max_shared_mem <= 0) return 5;

  int major_capability, minor_capability;
  cudaDeviceGetAttribute(&major_capability, cudaDevAttrComputeCapabilityMajor,
                         dev);
  cudaDeviceGetAttribute(&minor_capability, cudaDevAttrComputeCapabilityMinor,
                         dev);
  if (major_capability * 10 + minor_capability < 75) return 5;
  int stages = 4;

  // a_type 运行时选择:kS8(W4A8,配 a_scales [M,1] fp32)/ kFloat16(W4A16)
  // is_bf16:激活/输出 bf16 档(selector 三族之一,(kS8,kU4B8,kBFloat16,kBFloat16))
  vllm::ScalarType a_type =
      a_is_s8 ? vllm::kS8 : (is_bf16 ? vllm::kBFloat16 : vllm::kFloat16);
  const float* a_s_ptr = (const float*)a_s;
  // U4B8 = 无符号 4bit + 8 偏置(GPTQ 对称量化语义,零点常量 8 烘进 dequant)。
  // U4(kU4)= AWQ 非对称语义(has_zp=true):dequant 走 q - zp(group),
  // b_z 须为 marlin_zero_points 布局((k/g, n/8) i32,见 repack.rs pack_marlin_z)。
  // 注:kU4 模板 constexpr has_zp=true 会无条件解引用 zp_ptr —— 仅限 use_zp=true
  // 且 b_z 有效时选用(nullptr → 非法地址,compute-sanitizer 定谳)。
  vllm::ScalarType b_type = use_zp ? vllm::kU4 : vllm::kU4B8;
  vllm::ScalarType c_type = is_bf16 ? vllm::kBFloat16 : vllm::kFloat16;
  vllm::ScalarType s_type = c_type;

  int max_par = 16;
  if (prob_n <= 4096) max_par = 16 * 8;
  int max_shared_mem_new = max_shared_mem;
  int rest_m = prob_m;
  int max_thread_m_blocks = 4;
  while (rest_m) {
    int par_count = rest_m / (max_thread_m_blocks * 16);
    if (par_count > max_par) par_count = max_par;
    int prob_m_split =
        par_count > 0 ? (par_count * (max_thread_m_blocks * 16)) : rest_m;

    int thread_k = thread_k_init;
    int thread_n = thread_n_init;

    int thread_m_blocks = div_ceil(prob_m_split, 16) < max_thread_m_blocks
                              ? div_ceil(prob_m_split, 16)
                              : max_thread_m_blocks;
    // 隔离开关:MARLIN_NO_M8=1 强制走非 m8 路径(定位 m8 相关问题用)
    bool m_block_size_8 = prob_m_split <= 8 && a_type.size_bits() == 16 &&
                          !getenv("MARLIN_NO_M8");

    exec_config_t exec_cfg;
    thread_config_t thread_tfg;
    if (thread_k != -1 && thread_n != -1) {
      thread_tfg = thread_config_t{thread_k, thread_n, default_threads};
      exec_cfg = exec_config_t{1, thread_tfg};
      if (prob_n % thread_n != 0 || prob_k % thread_k != 0) return 4;
    } else {
      // Auto config
      exec_cfg = determine_exec_config(
          a_type, b_type, c_type, s_type, prob_m_split, prob_n, prob_k,
          thread_m_blocks, m_block_size_8, num_bits, group_size, has_act_order,
          is_k_full, has_zp, is_zp_float, is_a_8bit, stages, max_shared_mem,
          sms);
      thread_tfg = exec_cfg.tb_cfg;
      if (thread_tfg.thread_n != -1 && !getenv("MARLIN_NO_OVERRIDE")) {
        if (prob_n / thread_tfg.thread_n *
                div_ceil(prob_m_split, thread_m_blocks * 16) * 4 <=
            sms) {
          if (is_valid_config({128, 64, 128}, thread_m_blocks, prob_m_split,
                              prob_n, prob_k, num_bits, group_size,
                              has_act_order, is_k_full, has_zp, is_zp_float,
                              is_a_8bit, stages, max_shared_mem_new)) {
            thread_tfg = {128, 64, 128};
            exec_cfg = {1, thread_tfg};
          }
        }
      }

      if (thread_tfg.thread_k == -1 && max_thread_m_blocks > 1) {
        max_thread_m_blocks--;
        continue;
      }
    }

    int num_threads = thread_tfg.num_threads;
    thread_k = thread_tfg.thread_k;
    thread_n = thread_tfg.thread_n;
    int blocks = sms * exec_cfg.blocks_per_sm;
    if (exec_cfg.blocks_per_sm > 1)
      max_shared_mem_new = max_shared_mem / exec_cfg.blocks_per_sm - 1024;

    int thread_k_blocks = thread_k / 16;
    int thread_n_blocks = thread_n / 16;

    if (!is_valid_config(thread_tfg, thread_m_blocks, prob_m_split, prob_n,
                         prob_k, num_bits, group_size, has_act_order,
                         is_k_full, has_zp, is_zp_float, is_a_8bit, stages,
                         max_shared_mem_new))
      return 3;

    auto kernel = get_marlin_kernel(
        a_type, b_type, c_type, s_type, thread_m_blocks, thread_n_blocks,
        thread_k_blocks, m_block_size_8, has_act_order, has_zp, group_blocks,
        num_threads, is_zp_float, stages);

    if (kernel == MarlinDefault) return 3;

    cudaFuncSetAttribute(kernel, cudaFuncAttributeMaxDynamicSharedMemorySize,
                         max_shared_mem_new);

    constexpr bool use_atomic_add = false;
    // 上游 dense 默认 true;kS8 部分和是 int32 位型,f16 全局往返会得到 inf
    constexpr bool use_fp32_reduce = true;
    bool part_use_atomic_add =
        use_atomic_add && div_ceil(prob_m_split, 64) * prob_n <= 2048;

    if (getenv("MARLIN_DEBUG"))
        std::fprintf(stderr,
                     "[marlin-v2] split=%d tmb=%d cfg={k%d,n%d,t%d} m8=%d gb=%d "
                     "blocks=%d smem=%d MNK=(%d,%d,%d) g=%d\n",
                     prob_m_split, thread_m_blocks, thread_k, thread_n,
                     num_threads, (int)m_block_size_8, group_blocks, blocks,
                     max_shared_mem_new, prob_m, prob_n, prob_k, group_size);

    kernel<<<blocks, num_threads, max_shared_mem_new, stream>>>(
        A_ptr, B_ptr, C_ptr, /*C_tmp*/ (int4*)c_tmp, /*bias*/ nullptr,
        /*a_scales*/ a_s_ptr, b_s_ptr, /*global_scale*/ nullptr,
        /*zp*/ (const int4*)b_z, /*g_idx*/ nullptr, num_groups,
        prob_m_split, prob_n, prob_k, lda, locks, /*has_bias*/ false,
        part_use_atomic_add, use_fp32_reduce, max_shared_mem_new);

    cudaError_t launch_err = cudaGetLastError();
    if (launch_err != cudaSuccess) {
      std::fprintf(stderr, "[marlin-v2] launch error: %s\n",
                   cudaGetErrorString(launch_err));
      return 6;
    }

    A_ptr += prob_m_split * (lda / (is_a_8bit ? 16 : 8));
    C_ptr += prob_m_split * (prob_n / 8);
    rest_m -= prob_m_split;
  }
  return 0;
}

}  // namespace

// ---------------------------------------------------------------------------
// extern "C" 薄壳
// ---------------------------------------------------------------------------

extern "C" {

// P5:设备空闲显存查询(DFlash 低内存自适应跳过的探针;当前设备已由 runner 设定)。
// 返回 0 = ok;1 = setDevice 失败;2 = cudaMemGetInfo 失败。
int marlin_mem_get_info_ffi(size_t* free_b, size_t* total_b, int dev) {
    if (cudaSetDevice(dev) != cudaSuccess) return 1;
    return cudaMemGetInfo(free_b, total_b) == cudaSuccess ? 0 : 2;
}

// S2.4a(roadmap):设备默认内存池 trim 变现。模型/草稿载入后,临时加载缓冲
// 已 free 但仍被 stream-ordered 默认池缓存,空闲显存探测看不到(S1.6 G3 实测
// ~2.58G 被 allocator 吸收)。trim 后缓存块归还驱动,free_mem_bytes 才是
// 真实可用量。只释放未在用的缓存块,不动存活分配(graph 专属池不受影响)。
// 返回 0 = ok;1 = setDevice 失败;2 = 取默认池失败;3 = trim 失败;4 = trim 后查询失败。
int marlin_mem_pool_trim_ffi(int dev, size_t* free_after, size_t* total_after) {
    if (cudaSetDevice(dev) != cudaSuccess) return 1;
    cudaMemPool_t pool = nullptr;
    if (cudaDeviceGetDefaultMemPool(&pool, dev) != cudaSuccess) return 2;
    if (cudaMemPoolTrimTo(pool, 0) != cudaSuccess) return 3;
    if (cudaMemGetInfo(free_after, total_after) != cudaSuccess) return 4;
    return 0;
}

// 泄露排查定谳(2026-09-21):默认池 release_threshold 默认 UINT64_MAX(永不
// 自动归还),请求热路径的瞬态页全部滞留池缓存 → nvidia-smi used 拉满、真 free
// 归零 → 下一请求的图池提交/跨池分配 OOM 或直接踩坏状态(Xid 31 / libcuda
// segfault)。置 0 = 空闲页即刻归还,free 对所有分配方可见。
// 返回 0 = ok;1 = setDevice 失败;2 = 取默认池失败;3 = setAttribute 失败。
int marlin_mem_pool_release_threshold_ffi(int dev, size_t threshold_bytes) {
    if (cudaSetDevice(dev) != cudaSuccess) return 1;
    cudaMemPool_t pool = nullptr;
    if (cudaDeviceGetDefaultMemPool(&pool, dev) != cudaSuccess) return 2;
    if (cudaMemPoolSetAttribute(pool, cudaMemPoolAttrReleaseThreshold, &threshold_bytes) != cudaSuccess)
        return 3;
    return 0;
}

// vLLM 增强 kernel(f16 A / u4 B / f16 C / f16 scales)。
// workspace:零初始化 i32,>= (prob_n/64) * 128(覆盖 max_par=128 上限)。
// 错误码:0 ok;3 无配置;4 形状非法;5 设备不支持;另见 cudaGetErrorString。
int marlin_gemm_v2_ffi(const void* A, const void* B, void* C, void* c_tmp,
                       const void* b_scales, int prob_m, int prob_n,
                       int prob_k, void* workspace, int group_size, int dev,
                       uintptr_t stream) {
  int sms = 0;
  cudaDeviceGetAttribute(&sms, cudaDevAttrMultiProcessorCount, dev);
  int num_groups = (group_size == -1) ? 1 : prob_k / group_size;
  return marlin_mm(A, B, C, c_tmp, const_cast<void*>(b_scales),
                   /*a_s=*/nullptr, /*a_is_s8=*/false, /*b_z=*/nullptr,
                   /*use_zp=*/false, prob_m, prob_n, prob_k, prob_k,
                   workspace, num_groups, group_size, dev,
                   (cudaStream_t)stream, -1, -1, sms, /*is_bf16=*/false);
}

// W4A8 变体:A = int8(已量化),a_scales = fp32 [M,1](per-token)。
// 其余契约与 marlin_gemm_v2_ffi 完全一致(B/scales/workspace 不变)。
int marlin_gemm_v2_w4a8_ffi(const void* A, const void* B, void* C,
                            void* c_tmp, const void* b_scales,
                            const void* a_scales, int prob_m, int prob_n,
                            int prob_k, void* workspace, int group_size,
                            int dev, uintptr_t stream, int is_bf16) {
  int sms = 0;
  cudaDeviceGetAttribute(&sms, cudaDevAttrMultiProcessorCount, dev);
  int num_groups = (group_size == -1) ? 1 : prob_k / group_size;
  return marlin_mm(A, B, C, c_tmp, const_cast<void*>(b_scales),
                   const_cast<void*>(a_scales), /*a_is_s8=*/true,
                   /*b_z=*/nullptr, /*use_zp=*/false,
                   prob_m, prob_n, prob_k, prob_k, workspace, num_groups,
                   group_size, dev, (cudaStream_t)stream, -1, -1, sms,
                   /*is_bf16=*/is_bf16 != 0);
}

// P5-Q1a:AWQ(kU4 非对称)通路。b_zeros = marlin_zero_points 布局
// ((k/g, n/8) i32,LSB-first nibble 沿 n,scale_perm + n-interleave 已烘焙)。
int marlin_gemm_v2_awq_ffi(const void* A, const void* B, void* C,
                           void* c_tmp, const void* b_scales,
                           const void* b_zeros, int prob_m, int prob_n,
                           int prob_k, void* workspace, int group_size,
                           int dev, uintptr_t stream) {
  int sms = 0;
  cudaDeviceGetAttribute(&sms, cudaDevAttrMultiProcessorCount, dev);
  int num_groups = (group_size == -1) ? 1 : prob_k / group_size;
  return marlin_mm(A, B, C, c_tmp, const_cast<void*>(b_scales),
                   /*a_s=*/nullptr, /*a_is_s8=*/false,
                   const_cast<void*>(b_zeros), /*use_zp=*/true,
                   prob_m, prob_n, prob_k, prob_k, workspace, num_groups,
                   group_size, dev, (cudaStream_t)stream, -1, -1, sms,
                   /*is_bf16=*/false);
}

}  // extern "C"
